---
- name: Configura MariaDB Galera Cluster
  hosts: bases_datos
  become: yes
  tasks:
    - name: Detiene el servicio de mariadb en todos los nodos
      service:
        name: mariadb
        state: stopped

    - name: Agregar configuración de Galera /etc/mysql/conf.d/galera.cnf
      template:
        src: templates/galera.cnf.j2
        dest: /etc/mysql/conf.d/galera.cnf
        owner: root
        group: root
        mode: 0644

    - name: Inicializar el cluster en el primer nodo
      shell: "galera_new_cluster"
      when: inventory_hostname == groups['bases_datos'][0]

    - name: Inicializar el resto de nodos
      service:
        name: mariadb
        state: started
      when: inventory_hostname != groups['bases_datos'][0]
      


