---
- name: Descarga archivos necesarios para crear el ambiente para Vagrant
  hosts: fisicos
  remote_user: greencore
  become: no
  tasks:
    - name: Descarga repositorio de Git
      git:
        repo: https://github.com/gabrielmb20/vagrant
        dest: /home/greencore/vagrant/
        update: yes


