---
- name: Instala servidor web Apache
  hosts: joomlas
  become: yes
  tasks:
    - name: Instala el paquete apache2 y dependencias necesarias
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - apache2
        - libapache2-mod-php5 
        - mariadb-common 
        - mariadb-client 
        - php5 
        - php5-mysql 
        - php-pear 
        - php5-cli
        - php5-common
        - php5-gd
        - php5-json
        - php5-mcrypt

    - name: Habilita módulos necesarios rewrite, proxy, proxy_http
      shell: "a2enmod rewrite proxy proxy_http"
        
    - name: Copia archivo de configuración del virtualhost
      copy:
        src: files/01-apache-virtualhost.conf
        dest: /etc/apache2/sites-available/01-rsn.ucr.ac.cr.conf
        owner: root
        group: root
        mode: 0644

    - name: Deshabilita virtualhost default y habilita el nuevo
      shell: "a2dissite 000-default.conf && a2ensite 01-rsn.ucr.ac.cr.conf"

    - name: Descarga copia del contenido de Joomla
      get_url:
        url: http://10.42.30.5/Vagrant/RSN/rsn.ucr.ac.cr.tar.bz2
        dest: /var/www/rsn.ucr.ac.cr.tar.bz2

    - name: Descomprime contenido de Joomla en /var/www/rsn.ucr.ac.cr/
      command: pbzip2 -d /var/www/rsn.ucr.ac.cr.tar.bz2


    - name: Reiniciar el servicio de apache para aplicar los cambios
      service:
        name: apache2
        state: restarted

