---
- name: Configura MariaDB Galera Cluster
  hosts: bases_datos
  become: yes
  tasks:
    - name: Detiene el servicio de mariadb en todos los nodos
      service:
        name: mariadb
        state: stopped

    - name: Agregar configuración de Galera /etc/mysql/conf.d/galera.cnf
      template:
        src: templates/galera.cnf.j2
        dest: /etc/mysql/conf.d/galera.cnf
        owner: root
        group: root
        mode: 0644

    - name: Inicializar el cluster en el primer nodo
      shell: "galera_new_cluster"
      when: inventory_hostname == groups['bases_datos'][0]

    - name: Inicializar el resto de nodos
      service:
        name: mariadb
        state: started
      when: inventory_hostname != groups['bases_datos'][0]

    - name: Instala dependencia MySQL-python
      pip:
        name: MySQL-python
        executable: pip2
        state: latest

    - name: Descarga respaldo de la base de datos en el primer nodo
      get_url:
        url: http://10.42.30.5/Vagrant/RSN/respaldo-mysql.sql.bz2
        dest: /tmp/respaldo-mysql.sql.bz2
      when: inventory_hostname == groups['bases_datos'][0]

    - name: Restaurar respaldo de la base de datos
      mysql_db:
        name: rsn
        state: import
        target: /tmp/respaldo-mysql.sql.bz2
      when: inventory_hostname == groups['bases_datos'][0]

    - name: Crear usuario para acceder las bases de datos desde los Joomla
      mysql_user:
        name: greencore
        password: greencore
        priv: "*.*:ALL"
        state: present
