---
- name: Instala servidor web Apache
  hosts: joomlas
  become: yes
  tasks:
    - name: Instala el paquete apache2 y dependencias necesarias
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - apache2
        - libapache2-mod-php5 
        - mariadb-common 
        - mariadb-client 
        - php5 
        - php5-mysql 
        - php-pear 
        - php5-cli
        - php5-common
        - php5-gd
        - php5-json
        - php5-mcrypt
        - pbzip2

    - name: Habilita módulos necesarios rewrite, proxy, proxy_http
      shell: "a2enmod rewrite proxy proxy_http"
        
    - name: Deshabilita virtualhost default
      shell: "a2dissite 000-default.conf"

    - name: Reiniciar el servicio de apache para aplicar los cambios
      service:
        name: apache2
        state: restarted

